# Generated by Django 3.1.5 on 2021-02-01 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
