# Generated by Django 3.1.7 on 2021-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0002_auto_20210312_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='drama_video_time',
            field=models.TimeField(null=True, verbose_name='DRAMA VIDEO TIME'),
        ),
    ]
