# Generated by Django 3.1.5 on 2021-02-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20210201_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='likes_user',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
    ]
