# Generated by Django 3.1.5 on 2021-02-02 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0004_auto_20210201_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='loves', to=settings.AUTH_USER_MODEL),
        ),
    ]
