# Generated by Django 3.1.5 on 2021-02-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sexType',
            field=models.CharField(choices=[('MAN', 'Man'), ('WOMAN', 'Woman')], default='MAN', max_length=9, verbose_name='Sex'),
        ),
    ]
